services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"     # comunicação com serviços
      - "15672:15672"   # painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order-system:
    build: .
    container_name: order-system
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data:
