spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/orderdb
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
